name: Build Hello World
on: push
jobs:
  setup:
    runs-on: windows-2019

    env:
      GRAALVM_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0
      JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0
      VISUAL_STUDIO_BUILD_TOOLS_TOME: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: check-project-state
      run: ls

    - name: install-compiler
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install visualstudio2017-workload-vctools -y --version 1.3.2

    - name: install-sdk
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install windows-sdk-10.1 -y --version 10.1.18362.1

    - name: setup-compiler-environment
      shell: cmd
      run: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

    - name: pathed-compiler
      run: echo "::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64"

    - name: check-compiler-state
      run: |
        ls "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64"
        (Get-Item -Path Env:Path).Value.Split(";")
        cl.exe

    - name: install-graalvm
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install graalvm -y --version 20.0.0

    - name: setup-graalvm
      run: echo "::add-path::C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0\bin"

    - name: check-graalvm-state
      run: java -version

    - name: setup-native-image
      shell: cmd
      run: |
        gu install native-image
        native-image.cmd

    - name: compile-java
      run: |
        javac A.java
        ls

    # we need to set the vc environment before calling native-image because the environment is lost between steps
    - name: compile-native
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"  
        native-image.cmd -H:+ReportExceptionStackTraces A
        ls

    - name: execute-build
      shell: cmd
      run: A.exe

    - name: upload-artifact
      uses: actions/upload-artifact@v1
      with:
        name: hello-world
        path: A.exe
