name: Build Hello World
on: push
jobs:
  setup:
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install-compiler
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install visualstudio2017-workload-vctools -y --version 1.3.2
    - name: setup-compiler-environment
      shell: cmd
      run: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - name: pathed-compiler
      shell: cmd
      run: echo "::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64
    - name: install-graalvm
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install graalvm -y --version 20.0.0
    - name: smoke-test-graalvm
      run: java --version
    - name: setup-native-image
      shell: cmd
      run: gu install native-image
