name: Build Hello World
on: push
jobs:
  setup:
    runs-on: windows-2019

    env:
      GRAALVM_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0
      JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0
      VISUAL_STUDIO_BUILD_TOOLS_TOME: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: check-project-state
      run: ls

    - name: install-compiler
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install visualstudio2017-workload-vctools -y --version 1.3.2

    - name: setup-compiler-environment
      shell: cmd
      run: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

    - name: pathed-compiler
      shell: cmd
      run: echo "::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64"

    - name: check-compiler-state
      run: ls "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64"

    - name: install-graalvm
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install graalvm -y --version 20.0.0
    - name: setup-graalvm
      run: echo "::add-path::C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0\bin"

    - name: smoke-test-graalvm
      run: java -version

    - name: setup-native-image
      shell: cmd
      run: gu install native-image

    - name: compile-java
      run: javac A.java

    - name: compile-native
      shell: cmd
      run: |
        set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64;%PATH%
        native-image.cmd -H:+ReportExceptionStackTraces A
