name: Build Hello World
on: push
jobs:
  setup:
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install-chocolatey
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: -h
  