name: Build Hello World
on: [push]
jobs:
  setup-graalvm-ce:
  runs-on: windows-2019
    steps:
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.1
        with:
          graalvm-version: "20.0.0"
          java-version: "java11"
      - name: setup-native-image
        run: |
          gu install native-image
