name: Build Hello World
on: push
jobs:
  setup:
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install-compiler
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install visualstudio2019buildtools -y --version 16.4.6.0
    - name: install-graalvm
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install graalvm -y --version 20.0.0
